test_that("it works", {
  x <- c(1,2,NA, 4)
  y <- c(10, 15, 16, NA)
  y_incor <- c(20, 15, 12, NA)

  expect_equal(b1(x, y), NA)
  expect_equal(b0(x, y), NA)
  expect_equal(celeration(x, y), NA_real_)
  expect_equal(accuracy_ratio(x, y, y_incor), NA)
  expect_equal(accuracy(x, y, y_incor), NA)
  expect_equal(predicted_values(x, y), NA)
  expect_equal(errors(x, y), NA)
  expect_equal(bounce_up(x, y), NA_real_)
  expect_equal(bounce_down(x, y), NA_real_)
  expect_equal(bounce_total(x, y), NA_real_)
})
